# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#theme: jekyll-theme-so-simple
remote_theme: mmistakes/so-simple-theme

head_scripts:
footer_scripts:

locale: zh-CN
title: "Kevin Wang"
description: "语默动静体安然"
baseurl: ""
url: "https://wkevin.gitee.io"
logo: "/images/mac.jpeg"
date_format: "%b %-d, %Y"
read_time: false
words_per_minute: # 200
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: "UA-2011187-2"
twitter:
  username: "wkevin27"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

# Collections
collections:
  ai:
    output: true
    permalink: /:collection/:path/
  auto:
    output: true
    permalink: /:collection/:path/
  it:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # AI defaults
  - scope:
      path: "_ai"
      type: ai
    values:
      layout: page
      comments: true
      share: true
  # Auto defaults
  - scope:
      path: "_auto"
      type: auto
    values:
      layout: page
      comments: true
      share: true
  # IT defaults
  - scope:
      path: "_it"
      type: it
    values:
      layout: page
      comments: true
      share: true

# Site Author
author:
  name: wKevin
  picture: /images/angry.bird.jpg
  email:
  twitter: "@wkevin27"
  links:
    - title: Weibo
      url: https://weibo.com/wkevin27
      icon: fab fa-weibo
    - title: Twitter
      url: https://twitter.com/wkevin27
      icon: fab fa-twitter-square
    - title: GitHub
      url: https://github.com/wkevin
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Weibo
    url: https://weibo.com/wkevin27
    icon: fab fa-weibo
  - title: Twitter
    url: https://twitter.com/wkevin27
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/wkevin
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square